// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Agregar_Usuarios_y_Roles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregar_Usuarios_y_Roles));
        
        string IMigrationMetadata.Id
        {
            get { return "202504020029421_Agregar_Usuarios_y_Roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
